Repository WildCodeSchool-2023-09/JS-RemoteFR-SACOD-P2-Moby-Dick, pull requests merged in 2023-10, with the labels that each got.

#55 Footer
  frontend/public/logo_wcs.png
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Footer.jsx
Labels: REVIEW REQUESTED

#57 Battle
  frontend/public/backgroundbeach.png
  frontend/public/backgroundearth.png
  frontend/public/backgroundforest.png
  frontend/public/backgroundgrass.png
  frontend/public/backgroundsea.png
  frontend/public/battlegroundbeach.jpg
  frontend/public/battlegroundbrown.jpg
  frontend/public/battlegroundcavern.jpg
  frontend/public/battlegroundearth.jpg
  frontend/public/battlegroundgrass.jpg
  frontend/public/battlegroundgrass2.jpg
  frontend/public/battlegroundsand.jpg
  frontend/public/battlegroundsnow.jpg
  frontend/public/battlegroundwater.jpg
  frontend/public/dresseur1.png
  frontend/public/dresseur10.png
  frontend/public/dresseur11.png
  frontend/public/dresseur12.png
  frontend/public/dresseur13.png
  frontend/public/dresseur14.png
  frontend/public/dresseur15.png
  frontend/public/dresseur16.png
  frontend/public/dresseur17.png
  frontend/public/dresseur18.png
  frontend/public/dresseur19.png
  frontend/public/dresseur2.png
  frontend/public/dresseur21.png
  frontend/public/dresseur22.png
  frontend/public/dresseur23.png
  frontend/public/dresseur24.png
  frontend/public/dresseur3.png
  frontend/public/dresseur4.png
  frontend/public/dresseur5.png
  frontend/public/dresseur6.png
  frontend/public/dresseur7.png
  frontend/public/dresseur8.png
  frontend/public/dresseur9.png
  frontend/src/App.css
  frontend/src/components/Battle.jsx
Labels: CONFLICTS RESOLVED

#62 Update App.css
  frontend/src/App.css
Labels: REVIEWED

#63 Update App.css
  frontend/src/App.css
Labels: REVIEWED
