Repository WildCodeSchool-2023-09/JS-RemoteFR-SACOD-P2-Moby-Dick, pull requests merged in 2023-11, with the labels that each got.

#58 Mise en place du Rooter
  frontend/pnpm-lock.yaml
  frontend/src/main.jsx
  frontend/yarn.lock
Labels: CHANGES REQUESTED

#65 add router for multi pages and css adjustements
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Hub.jsx
  frontend/src/components/MenuPlayer.jsx
  frontend/src/components/PokeCenter.jsx
  frontend/src/main.jsx
Labels: CORRECTIONS DONE

#66 PokeCenter Route
  frontend/package-lock.json
  frontend/src/components/Hub.jsx
  frontend/src/main.jsx
  frontend/yarn.lock
Labels: REVIEWED

#69 Css debug
  backend/yarn.lock
  frontend/src/App.css
  frontend/src/components/Home.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/main.jsx
  frontend/yarn.lock
  yarn.lock
Labels: REVIEW REQUESTED

#71 add Pokedex with API
  frontend/src/components/MenuPlayer.jsx
  frontend/src/components/Pokedex.jsx
  frontend/src/main.jsx
Labels: CONFLICTS RESOLVED

#76 Css pokedex
  frontend/index.html
  frontend/public/pokecenter.png
  frontend/public/pokedexbackground.png
  frontend/src/App.css
  frontend/src/components/MenuPlayer.jsx
  frontend/src/components/Pokedex.jsx
  frontend/src/main.jsx
Labels: REVIEW REQUESTED

#77 fix css
  frontend/src/App.css
Labels: REVIEWED

#83 Pokeshop
  frontend/public/pokeshop.png
  frontend/src/App.css
  frontend/src/components/Hub.jsx
  frontend/src/components/Pokeshop.jsx
  frontend/src/main.jsx
Labels: REVIEWED

#87 Fight system
  frontend/src/App.css
  frontend/src/components/Battle.jsx
  frontend/src/components/FightSystem.jsx
  frontend/src/components/MenuPlayer.jsx
  frontend/src/components/Pokedex.jsx
  frontend/src/components/PokemonContext.jsx
  frontend/src/main.jsx
Labels: REVIEWED

#95 add animation on attack buton
  frontend/src/App.css
  frontend/src/components/FightSystem.jsx
Labels: REVIEWED

#92 Ajout fonction heal PokeCenter
  frontend/src/components/PokeCenter.jsx
Labels: REVIEWED

#97 css fighter system
  frontend/public/dialogue.png
  frontend/public/katana.png
  frontend/public/katana1.png
  frontend/public/katana2.png
  frontend/public/zarbi.png
  frontend/src/App.css
  frontend/src/components/FightSystem.jsx
  frontend/src/components/Pokedex.jsx
Labels: REVIEWED

#100 Fix css
  frontend/public/katana.png
  frontend/public/katana1.png
  frontend/public/katana2.png
  frontend/src/App.css
  frontend/src/components/BattleArene.jsx
  frontend/src/components/FightSystem.jsx
  frontend/src/main.jsx
Labels: REVIEWED

#98 page 404 + css
  frontend/package-lock.json
  frontend/package.json
  frontend/public/404img.png
  frontend/public/Decor404.jpg
  frontend/public/Diglet.png
  frontend/src/App.css
  frontend/src/components/NavBar.jsx
  frontend/src/components/NotFound.jsx
  frontend/src/main.jsx
Labels: CONFLICTS RESOLVED

#99 Starter.2
  frontend/src/App.css
  frontend/src/components/Pokedex.jsx
  frontend/src/components/Starter.jsx
Labels: CONFLICTS

#103 fix css
  frontend/src/App.css
Labels: REVIEW REQUESTED
